name: montycat
description: >
  Montycat Dart client: the self-hosted NoSQL + vector database for Dart and Flutter with built-in AI semantic search for RAG & AI agents, async operations, real-time subscriptions, in-memory and persistent storage.
version: 1.0.9
environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  hashlib: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - vector-database
  - semantic-search
  - rag
  - embeddings
  - nosql

license: MIT
homepage: https://montygovernance.com
documentation: https://pub.dev/documentation/montycat/latest/
